### ISSUE TITLE
Invalid Item displayed on hover.

### ISSUE THREAD

**Issue by mibby** [dadus33/ChatItem#12]
Paper dev 600 (Spigot 1.13.2)
ChatItem compiled as of commit https://github.com/dadus33/ChatItem/commit/d69c0e02f3d48dfd08813fbe465511c5e7e10dc3

@WOLFI3654 Any ideas why I'm not able to output an item in chat?

The fully functional item.
![link](https://i.imgur.com/s9OiHWc.png)

The item when trying to hover over it after typing [i] in chat.
![link2](https://i.imgur.com/Rgwvc0u.png)

How the item is configured.
```
  Super_Flare_Gun:
    id: WOODEN_HOE
    slot: Arbitrary
    durability: 5
    name: '&eSupersonic Flare Gun'
    lore:
    - '&8&m--------&f&l &nGeneral&8 &m--------'
    - '&cGun'
    - ''
    - '&8&m-------------------------'
    - ''
    - '&7Click to call for extraction.'
    - '&7Extraction time: 30 seconds'
    - ''
```
