### ISSUE TITLE
Hover text not applying to entire item measage

### ISSUE THREAD

**Issue by phoenixztt** [dadus33/ChatItem#43]
There is an issue where the hover text breaks when the color code changes, for example when I set it to 
```yml
  # The format of the item placeholders.
  name-format: "&5[&b{name} {amount}&5]&r"
  # The format of the {amount} placeholder.
  # {times} correspond to amount of item
  amount-format: "x{times}"
  ```

Only the very last `&5]` has the hover text instead of the entire message

<img width="544" alt="image" src="https://user-images.githubusercontent.com/97313380/183058547-e2104a72-4c3f-4b7a-bcb3-957a37ad19b5.png">

*Hovers text only shows on that last character*
